2023-02-26 16:41:40,820 - root - INFO - The user requested a forecast from the API.
2023-02-26 16:41:54,999 - root - INFO - The user requested a forecast from the API.
2023-02-26 16:42:03,843 - root - ERROR - There was an issue retrieving the forecast from the API: 404 Client Error: Not Found for url: http://api.openweathermap.org/data/2.5/forecast?q=jfdksal%2Cjf&units=imperial&appid=eec85de375ab459abeb6100d4a9bad9b
Traceback (most recent call last):
  File "c:\Users\Thurman\Desktop\School\spring_2023\development_capstone\week_six_api\api_lab.py", line 70, in get_forecast
    response.raise_for_status() # Raise exception for 400 or 500 errors
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thurman\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://api.openweathermap.org/data/2.5/forecast?q=jfdksal%2Cjf&units=imperial&appid=eec85de375ab459abeb6100d4a9bad9b
2023-02-26 16:42:19,337 - root - INFO - The user requested a forecast from the API.
